---
# Complete Vivo server

- hosts: all
  become: yes
  roles:
    - geerlingguy.mysql

- hosts: all
  become: yes
  roles:
    - geerlingguy.apache

- hosts: all
  become: yes
  roles:
    - williamyeh.oracle-java

- name: Download the vivo src locally for resuse
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: download vivo source to the local download directory
    get_url:
      url: https://github.com/vivo-project/VIVO/releases/download/{{ vivo_version }}/vivo-{{ vivo_version }}.zip
      dest: downloads/{{ vivo_version }}/vivo-{{ vivo_version }}.zip

- hosts: all
  become: yes
  environment:
    - CATALINA_BASE: "/usr/share/tomcat"
    - NAME: "tomcat"
  roles:
    - bertvv.tomcat

- hosts: all
  become: yes
  environment:
    - CATALINA_BASE: "/usr/share/tomcat"
    - NAME: "tomcat"
  tasks:
    - user: name={{app_user}} state=present
      become: yes
    - include: tasks/devtools.yml
    - include: tasks/ant.yml
    - include: tasks/apache2.yml
    - include: tasks/vivo.yml
