---
# Complete Vivo server

- hosts: app
  become: yes
  roles:
    - geerlingguy.mysql

- hosts: app
  become: yes
  roles:
    - geerlingguy.apache

- hosts: app
  become: yes
  roles:
    - williamyeh.oracle-java

- hosts: app
  become: yes
  roles:
    - bertvv.tomcat

- hosts: app
  become: yes
  environment:
    - CATALINA_BASE: "/usr/share/tomcat"
    - NAME: "tomcat"
  tasks:
    - user: name={{app_user}} state=present
      become: yes
    - include: tasks/devtools.yml
    - include: tasks/ant.yml
    - include: tasks/apache2.yml
    - include: tasks/vivo.yml
