---
# Complete Vivo server
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  roles:
    - geerlingguy.mysql
    - williamyeh.oracle-java
  tasks:
    - user: name={{app_user}} state=present
      become: yes
    - include: tasks/devtools.yml
    - include: tasks/ant.yml
    - include: tasks/apache2.yml
