---

    #src: https://github.com/vivo-project/VIVO/releases/download/{{ vivo_version }}/vivo-{{ vivo_version }}.zip
    #copy: no
- name: checkout the vivo app code from source control
  unarchive:
    src: files/vivo-{{ vivo_version }}.zip
    dest: /opt
    copy: yes
    owner: tomcat
    group: tomcat
- name: Create Vivo build properties
  command: cp "example.build.properties" "build.properties"
  args:
      chdir: "{{ vivo_build_path }}"
  become_user: tomcat
- name: Configure Vivo build properties
  lineinfile:
    dest: "/opt/vivo-{{ vivo_version }}/build.properties"
    regexp: "tomcat.home = /usr/local/tomcat"
    line: "tomcat.home = {{ tomcat_home_path }}"
- name: Build Vivo
  command: ant all
  args:
    chdir: "/opt/vivo-{{ vivo_version }}"
- name: Change Vivo Owner and Group
  file:
    path: "{{ vivo_home_path }}"
    recurse: yes
    owner: tomcat
    group: tomcat
- command: cp example.runtime.properties runtime.properties
  args:
    chdir: "{{ vivo_home_path }}"
  become_user: tomcat
- name: Customize Vigro DB Username
  replace:
    dest: "{{ vivo_home_path }}/runtime.properties"
    regexp: "vitrodbUsername"
    replace: "{{ vitro_db_username }}"
- name: Set Vitro DB Password
  replace:
    dest: "{{ vivo_home_path }}/runtime.properties"
    regexp: "vitrodbPassword"
    replace: "{{ vitro_db_password }}"
- name: Set Vigro Domain Name
  replace:
    dest: "{{ vivo_home_path }}/runtime.properties"
    regexp: "vivo.mydomain.edu"
    replace: "{{ vivo_domain }}"
- name: Create application setup file
  command: cp config/example.applicationSetup.n3 config/applicationSetup.n3
  args:
      chdir: "{{ vivo_home_path }}"
  become_user: tomcat
- name: Create developer properties file
  command: cp config/example.developer.properties config/developer.properties
  args:
      chdir: "{{ vivo_home_path }}"
  become_user: tomcat
- name: Start up Tomcat
  command: tomcat start

