---

- name: Clone theme to vivo server
  git:
    repo: https://github.com/tulibraries/tuvivo_theme.git
    dest: "{{ vivo_build_path }}/webapp/src/main/webapp/themes/tuvivo"
    version: "{{ vivo_theme_branch }}"

- name: Rebuild Vivo
  command: mvn install -s installer/settings.xml
  args:
    chdir: "{{ vivo_build_path }}"

- name: Change Vivo Owner and Group
  file:
    path: "{{ vivo_home_path }}"
    recurse: yes
    owner: tomcat
    group: tomcat

- name: Restart Tomcat server
  service:
    name: tomcat
    state: restarted
