---

- name: Create vivo release download directory
  local_action:
    module: file
    path: downloads/{{ vivo_version }}
    state: directory
  become: no

- name: Download vivo release
  local_action:
    module: get_url
    url: "{{ vivo_download_url }}"
    dest: "downloads/{{ vivo_version }}/vivo-{{ vivo_version }}.zip"
  become: no

- name: Copy Vivo archive to the installation directory
  copy:
    src: "downloads/{{ vivo_version }}/vivo-{{ vivo_version }}.zip"
    dest: /opt

#
# [NOTE:] Encountered problem with `unarchive`. It fails
# extracting certain doc files. Workaround `command: unzip`
# instead. Return to using `unarchive` when problem resolved.
# Looks likely to be fixed in 2.1.1
#
#- name: checkout the vivo app code from source control
#  unarchive:
#    src: "/opt/vivo-{{ vivo_version }}.zip"
#    dest: /opt
#    copy: no

- name: Unzip the vivo archive
  command: "unzip vivo-{{ vivo_version }}.zip"
  args:
      chdir: "/opt"

- name: Create Vivo build properties
  template:
    src: "templates/build.properties.j2"
    dest: "{{ vivo_build_path }}/build.properties"

- name: Build Vivo
  command: ant all
  args:
    chdir: "/opt/vivo-{{ vivo_version }}"

- name: Change Vivo Owner and Group
  file:
    path: "{{ vivo_home_path }}"
    recurse: yes
    owner: tomcat
    group: tomcat

- name: Create Vivo runtime properties
  template:
    src: "templates/runtime.properties.j2"
    dest: "{{ vivo_home_path }}/runtime.properties"
    owner: tomcat
    group: tomcat

- name: Create application setup file
  template:
    src: "templates/applicationSetup.n3.j2"
    dest: "{{ vivo_home_path }}/config/applicationSetup.n3"
    owner: tomcat
    group: tomcat

- name: Create developer properties file
  copy:
    src: "templates/developer.properties.j2"
    dest: "{{ vivo_home_path }}/config/developer.properties"
    owner: tomcat
    group: tomcat

- name: Restart Tomcat server
  service:
    name: tomcat
    state: restarted
