---

- name: Get vivo app
  copy:
    src: "files/vivo-{{ vivo_version }}.zip"
    dest: /opt
# 
# [NOTE:] Encountered problem with `unarchive`. It fails
# extracting certain doc files. Workaround `command: unzip`
# instead. Return to using `unarchive` when problem resolved.
#
#- name: checkout the vivo app code from source control
#  unarchive:
#    src: /opt/vivo-{{ vivo_version }}.zip
#    dest: /opt
#    copy: no
- name: unzip the vivo archive
  command: "unzip vivo-{{ vivo_version }}.zip"
  args:
      chdir: "/opt"
- name: Create Vivo build properties
  command: cp "example.build.properties" "build.properties"
  args:
      chdir: "{{ vivo_build_path }}"
- name: Configure Vivo build properties
  lineinfile:
    dest: "/opt/vivo-{{ vivo_version }}/build.properties"
    regexp: "tomcat.home = /usr/local/tomcat"
    line: "tomcat.home = {{ tomcat_home_path }}"
- name: Build Vivo
  command: ant all
  args:
    chdir: "/opt/vivo-{{ vivo_version }}"
- name: Change Vivo Owner and Group
  file:
    path: "{{ vivo_home_path }}"
    recurse: yes
    owner: tomcat
    group: tomcat
- command: cp example.runtime.properties runtime.properties
  args:
    chdir: "{{ vivo_home_path }}"
  become_user: tomcat
- name: Set SMTP Server
  replace:
    dest: "{{ vivo_home_path }}/runtime.properties"
    regexp: "smtp.mydomain.edu"
    replace: "{{ smtp_server }}"
- name: Customize Vigro DB Username
  replace:
    dest: "{{ vivo_home_path }}/runtime.properties"
    regexp: "vitrodbUsername"
    replace: "{{ vitro_db_username }}"
- name: Set Vitro DB Password
  replace:
    dest: "{{ vivo_home_path }}/runtime.properties"
    regexp: "vitrodbPassword"
    replace: "{{ vitro_db_password }}"
- name: Set Vigro Domain Name
  replace:
    dest: "{{ vivo_home_path }}/runtime.properties"
    regexp: "mydomain.edu"
    replace: "{{ vivo_domain }}"
- name: Create application setup file
  command: cp config/example.applicationSetup.n3 config/applicationSetup.n3
  args:
      chdir: "{{ vivo_home_path }}"
  become_user: tomcat
- name: Create developer properties file
  command: cp config/example.developer.properties config/developer.properties
  args:
      chdir: "{{ vivo_home_path }}"
  become_user: tomcat
- name: Start up Tomcat
  command: tomcat start
