---

- name: Clone Vitro to vivo server
  git:
    repo: https://github.com/vivo-project/Vitro.git
    dest: "{{ vitro_build_path }}"
    version: "{{ vitro_branch }}"

- name: Clone Vivo to vivo server
  git:
    repo: https://github.com/vivo-project/VIVO.git
    dest: "{{ vivo_build_path }}"
    version: "{{ vivo_commit }}"

- name: Create Vivo install settings
  template:
    src: install.xml.j2
    dest: "{{ vivo_build_path }}/installer/install.xml"

- name: Build Vivo
  command: mvn install -s installer/install.xml
  args:
    chdir: "{{ vivo_build_path }}"

- name: Change Vivo Owner and Group
  file:
    path: "{{ vivo_home_path }}"
    recurse: yes
    owner: tomcat
    group: tomcat

- name: Create Vivo runtime properties
  template:
    src: templates/runtime.properties.j2
    dest: "{{ vivo_home_path }}/runtime.properties"
    owner: tomcat
    group: tomcat

- name: Create application setup file
  template:
    src: templates/applicationSetup.n3.j2
    dest: "{{ vivo_home_path }}/config/applicationSetup.n3"
    owner: tomcat
    group: tomcat

- name: Restart Tomcat server
  service:
    name: tomcat
    state: restarted
